"""Initial migration

Revision ID: 846683180bf0
Revises: 
Create Date: 2024-07-25 01:21:08.316268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '846683180bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_constraint('skus_ibfk_3', type_='foreignkey')
        batch_op.drop_column('per_unit')
        batch_op.drop_column('valid_to')
        batch_op.drop_column('amount')
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('unit')
        batch_op.drop_column('valid_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('unit', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('subcategory_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('per_unit', mysql.VARCHAR(length=10), nullable=True))
        batch_op.create_foreign_key('skus_ibfk_3', 'subcategories', ['subcategory_id'], ['id'])
        batch_op.drop_column('price')

    # ### end Alembic commands ###
