"""Set foreign key constraints to ON DELETE CASCADE

Revision ID: e6edeb642924
Revises: ec4ea2d8a5cb
Create Date: 2024-07-26 16:50:36.040258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6edeb642924'
down_revision = 'ec4ea2d8a5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_constraint('skus_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('skus_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('skus_ibfk_2', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('skus_ibfk_3', 'subcategories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###
