"""Add subcategories and update SKU model

Revision ID: ec4ea2d8a5cb
Revises: 2219cda9918b
Create Date: 2024-07-26 16:15:09.095679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4ea2d8a5cb'
down_revision = '2219cda9918b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
